title: Venu Devadi
logo: /assets/img/headshot_circle.png
description: "LLM & NLP Enthusiast | 📧 [Email](mailto:venukrishnadevadi@gmail.com) | 💻 [GitHub](https://github.com/venukrishna-devadi)"
show_downloads: true
theme: jekyll-theme-minimal
